/**
 * web3-auth-svc — Ergo auth service for libpam-web3.
 *
 * Self-contained HTTPS server: serves the signing page and handles
 * auth callbacks.  Port is derived from the chain name via CRC32.
 * TLS uses the certs generated by the libpam-web3 postinst.
 *
 * Routes:
 *   GET  /              — Signing page HTML
 *   GET  /engine.js     — Signing page JS
 *   GET  /auth/pending/:session_id   — Return session JSON
 *   POST /auth/callback/:session_id  — Accept Schnorr signature, write .sig file
 *
 * .sig file format (JSON):
 *   { chain, signature, public_key, otp, machine_id }
 *   chain = "ergo" — tells the PAM module which verification plugin to use
 *
 * SPECIAL profile: S8 P10 E7 C5 I8 A8 L7
 *   P10: Auth boundary — validate every input, trust nothing from the network.
 *   E7: Long-running daemon — must not crash, must not leak.
 *
 * Cryptographic verification:
 *   Schnorr proveDlog proof verified in `schnorr.ts` against the EIP-0044 ADH
 *   message format. This is a safety check — the PAM plugin independently
 *   derives the address from the pubkey.
 */

import * as https from "node:https";
import * as fs from "node:fs";
import * as path from "node:path";
import { timingSafeEqual } from "node:crypto";
import { verifySchnorrProof } from "./schnorr";

// ── Constants ──────────────────────────────────────────────────────────

const CHAIN_NAME = "ergo";
const DEFAULT_PENDING_DIR = "/run/libpam-web3/pending";
let PENDING_DIR = DEFAULT_PENDING_DIR;
const MAX_BODY_SIZE = 16_384;

function chainPort(chain: string): number {
  let crc = 0xFFFFFFFF;
  for (let i = 0; i < chain.length; i++) {
    crc ^= chain.charCodeAt(i);
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
    }
  }
  return 1024 + ((crc ^ 0xFFFFFFFF) >>> 0) % 64511;
}

const SESSION_ID_RE = /^[0-9a-f]{32}$/;
const HEX_RE = /^[0-9a-fA-F]+$/;

// ── Config ─────────────────────────────────────────────────────────────

const DEFAULT_CERT = "/etc/libpam-web3/tls/cert.pem";
const DEFAULT_KEY = "/etc/libpam-web3/tls/key.pem";
const DEFAULT_PAGES_DIR = "/usr/share/blockhost/signing-pages";

interface ServerConfig {
  port: number;
  pending_dir: string;
  cert: string;
  key: string;
  pages_dir: string;
}

function parseToml(content: string): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};
  let section = "";

  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    const secMatch = line.match(/^\[([a-zA-Z_][a-zA-Z0-9_]*)\]$/);
    if (secMatch?.[1]) {
      section = secMatch[1];
      result[section] = result[section] || {};
      continue;
    }

    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
    if (!kvMatch?.[1] || !kvMatch[2] || !section) continue;

    const key = kvMatch[1];
    const val = kvMatch[2].trim();

    if (val.startsWith('"') && val.endsWith('"')) {
      result[section]![key] = val.slice(1, -1);
    } else {
      const num = Number(val);
      result[section]![key] = Number.isNaN(num) ? val : num;
    }
  }

  return result;
}

function loadConfig(configPath: string): ServerConfig {
  const defaultPort = chainPort(CHAIN_NAME);
  const defaults: ServerConfig = {
    port: defaultPort,
    pending_dir: DEFAULT_PENDING_DIR,
    cert: DEFAULT_CERT,
    key: DEFAULT_KEY,
    pages_dir: path.join(DEFAULT_PAGES_DIR, CHAIN_NAME),
  };

  let content: string;
  try {
    content = fs.readFileSync(configPath, "utf8");
  } catch {
    return defaults;
  }

  const toml = parseToml(content);
  const sec = toml["server"] || {};

  return {
    port: typeof sec.port === "number" ? sec.port : defaults.port,
    pending_dir: String(sec.pending_dir || defaults.pending_dir),
    cert: String(sec.cert || defaults.cert),
    key: String(sec.key || defaults.key),
    pages_dir: String(sec.pages_dir || defaults.pages_dir),
  };
}

// ── Validation ────────────────────────────────────────────────────────

function isValidSessionId(id: string): boolean {
  return SESSION_ID_RE.test(id);
}

function isValidHex(str: string): boolean {
  return str.length > 0 && str.length % 2 === 0 && HEX_RE.test(str);
}

// ── Payload Types ─────────────────────────────────────────────────────

interface CallbackPayload {
  signature: string;
  key: string;
  otp: string;
  machineId: string;
}

function parseCallbackBody(body: string): CallbackPayload | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    return null;
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return null;
  }

  const obj = parsed as Record<string, unknown>;
  const keys = Object.keys(obj);

  if (keys.length !== 4) return null;
  if (typeof obj["signature"] !== "string") return null;
  if (typeof obj["key"] !== "string") return null;
  if (typeof obj["otp"] !== "string") return null;
  if (typeof obj["machineId"] !== "string") return null;

  if (obj["otp"].length > 16 || obj["machineId"].length > 128) return null;

  if (!isValidHex(obj["signature"])) return null;
  if (!isValidHex(obj["key"])) return null;

  return {
    signature: obj["signature"],
    key: obj["key"],
    otp: obj["otp"],
    machineId: obj["machineId"],
  };
}

// ── Session ───────────────────────────────────────────────────────────

interface SessionData {
  otp: string;
  machine_id: string;
}

function readSession(sessionId: string): SessionData | null {
  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  try {
    const content = fs.readFileSync(jsonPath, "utf8");
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== "object" || parsed === null) return null;
    const obj = parsed as Record<string, unknown>;
    if (typeof obj["otp"] !== "string" || typeof obj["machine_id"] !== "string") {
      return null;
    }
    return { otp: obj["otp"], machine_id: obj["machine_id"] };
  } catch {
    return null;
  }
}

// ── Verification & .sig Write ─────────────────────────────────────────

interface ErgoSigFile {
  chain: "ergo";
  signature: string;
  public_key: string;
  otp: string;
  machine_id: string;
}

function validateAndWriteSig(sessionId: string, payload: CallbackPayload): string | null {
  const sigPath = path.join(PENDING_DIR, `${sessionId}.sig`);
  if (fs.existsSync(sigPath)) return "session already processed";

  const session = readSession(sessionId);
  if (!session) return "session not found or malformed";

  // Timing-safe OTP comparison
  const otpA = Buffer.from(payload.otp);
  const otpB = Buffer.from(session.otp);
  if (otpA.length !== otpB.length) return "otp mismatch";
  if (!timingSafeEqual(otpA, otpB)) return "otp mismatch";

  if (payload.machineId !== session.machine_id) return "machine_id mismatch";

  // Public key: must be 33 bytes (66 hex chars), compressed secp256k1
  if (payload.key.length !== 66) {
    return `public key must be 33 bytes (66 hex), got ${payload.key.length} hex chars`;
  }
  const keyPrefix = payload.key.slice(0, 2).toLowerCase();
  if (keyPrefix !== "02" && keyPrefix !== "03") {
    return `invalid compressed pubkey prefix: ${keyPrefix} (expected 02 or 03)`;
  }

  // Verify Schnorr proveDlog proof
  const message = `Authenticate to ${payload.machineId} with code: ${payload.otp}`;
  const verifyErr = verifySchnorrProof(payload.signature, payload.key, message);
  if (verifyErr) return verifyErr;

  // Write .sig file (atomic: write tmp, rename)
  const sigContent: ErgoSigFile = {
    chain: "ergo",
    signature: payload.signature,
    public_key: payload.key,
    otp: payload.otp,
    machine_id: payload.machineId,
  };

  const tmpPath = path.join(PENDING_DIR, `${sessionId}.sig.tmp`);
  try {
    fs.writeFileSync(tmpPath, JSON.stringify(sigContent));
    fs.renameSync(tmpPath, sigPath);
  } catch (err) {
    try { fs.unlinkSync(tmpPath); } catch { /* tmp may not exist */ }
    return `sig file write failed: ${err instanceof Error ? err.message : String(err)}`;
  }

  console.log(`[AUTH] Verified Schnorr proof for session ${sessionId}`);
  return null;
}

// ── Route Handlers ────────────────────────────────────────────────────

type HttpResponse = import("node:http").ServerResponse;
type HttpRequest = import("node:http").IncomingMessage;

function sendResponse(
  res: HttpResponse,
  statusCode: number,
  body: string,
  contentType = "text/plain",
): void {
  res.writeHead(statusCode, { "Content-Type": contentType });
  res.end(body);
}

function handleGetPending(sessionId: string, res: HttpResponse): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  let contents: string;
  try {
    contents = fs.readFileSync(jsonPath, "utf8");
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }

  sendResponse(res, 200, contents, "application/json");
}

function handlePostCallback(
  sessionId: string,
  req: HttpRequest,
  res: HttpResponse,
): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const contentType = req.headers["content-type"] || "";
  if (!contentType.includes("application/json")) {
    sendResponse(res, 400, "Content-Type must be application/json");
    return;
  }

  const chunks: Buffer[] = [];
  let bodySize = 0;
  let aborted = false;

  req.on("data", (chunk: Buffer) => {
    bodySize += chunk.length;
    if (bodySize > MAX_BODY_SIZE) {
      if (!aborted) {
        aborted = true;
        sendResponse(res, 413, "body too large");
        req.destroy();
      }
      return;
    }
    chunks.push(chunk);
  });

  req.on("end", () => {
    if (aborted) return;

    const body = Buffer.concat(chunks).toString("utf8").trim();
    const payload = parseCallbackBody(body);
    if (!payload) {
      sendResponse(res, 400, "invalid request body");
      return;
    }

    const error = validateAndWriteSig(sessionId, payload);

    if (error === null) {
      sendResponse(res, 200, "OK");
    } else if (error === "session already processed") {
      sendResponse(res, 409, "Conflict");
    } else if (error === "session not found or malformed") {
      sendResponse(res, 404, "Not Found");
    } else {
      console.error(`[AUTH] Callback rejected for session ${sessionId}: ${error}`);
      sendResponse(res, 400, "verification failed");
    }
  });

  req.on("error", () => { /* connection closed by client */ });
}

// ── Static file serving ───────────────────────────────────────────────

let PAGES_DIR = "";

function serveFile(
  res: HttpResponse,
  filePath: string,
  contentType: string,
): void {
  let data: Buffer;
  try {
    data = fs.readFileSync(filePath);
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }
  res.writeHead(200, {
    "Content-Type": contentType,
    "Content-Length": data.length,
  });
  res.end(data);
}

// ── Server ────────────────────────────────────────────────────────────

function main(): void {
  const configPath = process.argv[2] || `/etc/web3-auth/${CHAIN_NAME}.toml`;
  const config = loadConfig(configPath);
  PENDING_DIR = config.pending_dir;
  PAGES_DIR = config.pages_dir;

  let tlsOpts: { cert: Buffer; key: Buffer };
  try {
    tlsOpts = {
      cert: fs.readFileSync(config.cert),
      key: fs.readFileSync(config.key),
    };
  } catch (err) {
    console.error(`[AUTH] TLS cert/key load failed: ${err}`);
    process.exit(1);
  }

  const server = https.createServer(tlsOpts, (req, res) => {
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Cache-Control", "no-store");

    const url = new URL(req.url || "/", "https://localhost");
    const pathname = url.pathname;

    // Signing page
    if (req.method === "GET" && (pathname === "/" || pathname === "/index.html")) {
      serveFile(res, path.join(PAGES_DIR, "index.html"), "text/html; charset=utf-8");
      return;
    }
    if (req.method === "GET" && pathname === "/engine.js") {
      serveFile(res, path.join(PAGES_DIR, "engine.js"), "application/javascript; charset=utf-8");
      return;
    }

    // Auth API
    const pendingMatch = pathname.match(/^\/auth\/pending\/([^/]+)$/);
    if (req.method === "GET" && pendingMatch?.[1]) {
      handleGetPending(pendingMatch[1], res);
      return;
    }

    const callbackMatch = pathname.match(/^\/auth\/callback\/([^/]+)$/);
    if (req.method === "POST" && callbackMatch?.[1]) {
      handlePostCallback(callbackMatch[1], req, res);
      return;
    }

    sendResponse(res, 404, "Not Found");
  });

  server.listen(config.port, "::", () => {
    console.log(`[AUTH] web3-auth-svc (${CHAIN_NAME}) on [::]:${config.port}`);
    console.log(`[AUTH] Pending dir: ${PENDING_DIR}`);
    console.log(`[AUTH] Pages: ${PAGES_DIR}`);
  });

  server.on("error", (err) => {
    console.error(`[AUTH] Server error: ${err}`);
    process.exit(1);
  });

  process.on("SIGTERM", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });

  process.on("SIGINT", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });
}

main();
